/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type koMessage from '../locales/ko/messages.json';

export type MessageKey = keyof typeof koMessage;

export type DevLocale = 'ko';
